### ISSUE TITLE
Errore on start

### ISSUE THREAD

**Issue by PKEv** [QTodoTxt/QTodoTxt2#61]
windows7 64x
try to start but get this:
```

Traceback (most recent call last):
  File "D:\QtProgects\QTodoTxt2\bin\qtodotxt.pyw", line 28, in <module>
    from qtodotxt2 import app
  File "D:\QtProgects\QTodoTxt2\bin\..\qtodotxt2\app.py", line 16, in <module>
    from qtodotxt2.main_controller import MainController
  File "D:\QtProgects\QTodoTxt2\bin\..\qtodotxt2\main_controller.py", line 14, in <module>
    class MainController(QtCore.QObject):
  File "D:\QtProgects\QTodoTxt2\bin\..\qtodotxt2\main_controller.py", line 60, in MainController
    @QtCore.pyqtSlot('QModelIndexList')
TypeError: C++ type 'QModelIndexList' is not supported as a pyqtSlot type argument type

```

**Comment by oroulet** [comment]
Nive to see you trying this @PKEv !!

Looks like a version issue, we have no idea what version is required ;-)

How did you installl qt and python ? with winpython? what version?

**Comment by PKEv** [comment]
And what kind of configuration do you have?
At me separately costs qt 5.7 and python 3,5

**Comment by oroulet** [comment]
I also have qt 4.7 and python 3.5...... on linux
maybe you are missing python3-pyqt5.qtquick?

@fuchsmich do you have any idea what the issue is?

**Comment by fuchsmich** [comment]
Honestly I don't really remember, how I got it working on Windows. Everything is so complicated here. ;)
I installed python from here https://www.python.org/downloads/ version 3.6.1 32bit and then pyqt via pip.
That's what I'm mainly using, when developing on Windows.

...but it also works with C:\WinPython-64bit-3.5.3.1Qt5

**Comment by oroulet** [comment]
btw look at README. I just updated with infor from a guy on windows

**Comment by fuchsmich** [comment]
My guess is, that you should try another version of pyqt.
